### PR TITLE
refactor: return potential error instead of discarding it

### PR DESCRIPTION
**Pull request by dimakis**

### CODE REVIEW

**Review by MichaelClifford — APPROVED** [review]
LGTM

**Review by MichaelClifford — APPROVED** [review]
LGTM!

**Comment by MichaelClifford** [comment]
@dimakis looks like I'm not an approver on this project. Maybe @anishasthana or @Maxusmusti can help get this approved.

**Review by asm582 — APPROVED** [review]
LGTM

**Pull request merged**
