### PR TITLE
fix vulnerabilities in image

### PR DESCRIPTION
**Pull request by jbusche**
This addresses the 7 known vulnerabilities found in the current instascale image, mentioned in issue https://github.com/project-codeflare/instascale/issues/33.

A manual build of the image scans clean, and when I replaced it in the deployment, the pod started up fine with my new image.

### CODE REVIEW

**Comment by jbusche** [comment]
I tried a test like this, but as it doesn't look like anything I did modified ./controllers, I don't think the test has anything to do with my changes.
```
go test -v ./controllers/
=== RUN   TestProviderSpecFromRawExtension
--- PASS: TestProviderSpecFromRawExtension (0.00s)
=== RUN   TestPodResourcesWithReplicas
--- PASS: TestPodResourcesWithReplicas (0.00s)
=== RUN   TestGetListOfPodResourcesFromOneGenericItem
--- PASS: TestGetListOfPodResourcesFromOneGenericItem (0.00s)
PASS
ok  	github.com/project-codeflare/instascale/controllers	0.099s
```

**Review by tedhtchang — COMMENTED** [review]
Should probably update the workflow go version in the workflow file https://github.com/project-codeflare/instascale/blob/3db6284598b469eff09149ed06a8e52a4f765497/.github/workflows/go.yml#L22

**Comment by asm582** [comment]
@jbusche did we do a manual integration test on the Openshift cluster post-image upgrade? 

@Maxusmusti can you please help us provision an environment?

**Comment by jbusche** [comment]
@asm582, I'm not sure how to do an integration test - if you can point me to it, would be glad to try and post the results of the test.

**Comment by jbusche** [comment]
I did testing on the AWS cluster, and Instascale worked great using my PR with the fixed image:
```
oc describe pod instascale-7b597f7d5c-nnlfz -n kube-system |grep Image
    Image:          quay.io/project-codeflare/instascale-controller:v0.0.3-jbuschetest2
```
I started it out with this:
```
cluster = Cluster(ClusterConfiguration(name='mnisttest', min_worker=1, max_worker=1, min_cpus=2, max_cpus=2, min_memory=4, max_memory=4, gpu=0, instascale=True, machine_types=['m5.xlarge', 'g4dn.xlarge'], auth=auth))
```
and with cluster.up() it struggled a bit, but eventually the pending pods went into Running state once it brought up two new nodes:
```
oc get nodes
NAME                                         STATUS   ROLES    AGE    VERSION
ip-10-0-149-10.us-east-2.compute.internal    Ready    master   7d5h   v1.24.0+9546431
ip-10-0-155-2.us-east-2.compute.internal     Ready    worker   7d5h   v1.24.0+9546431
ip-10-0-174-125.us-east-2.compute.internal   Ready    worker   18m    v1.24.0+9546431
ip-10-0-182-120.us-east-2.compute.internal   Ready    worker   21m    v1.24.0+9546431
```
I've now launched the batch job:
```
! torchx run -s ray -cfg dashboard_address=mnisttest-head-svc.default.svc:8265,requirements=requirements.txt dist.ddp -j 2x4 --gpu 0 --script mnist.py
And it's succeeded:
<JobStatus.SUCCEEDED: 'SUCCEEDED'>
```
Then, deleting the appwrapper results in the extra nodes getting deleted:
```
oc logs -f instascale-7b597f7d5c-nnlfz -n kube-system
...
I0301 01:45:18.300781       1 appwrapper_controller.go:420] Appwrapper deleted scale-down machineset: mnisttest 
I0301 01:45:18.306013       1 appwrapper_controller.go:455] Delete successful
I0301 01:45:18.320122       1 appwrapper_controller.go:455] Delete successful
```
and
```
oc get nodes
NAME                                        STATUS   ROLES    AGE    VERSION
ip-10-0-149-10.us-east-2.compute.internal   Ready    master   7d5h   v1.24.0+9546431
ip-10-0-155-2.us-east-2.compute.internal    Ready    worker   7d5h   v1.24.0+9546431
```

**Review by asm582 — APPROVED** [review]
LGTM

**Pull request merged**
