### PR TITLE
rhoaieng 1094

### PR DESCRIPTION
**Pull request by KPostOffice**
we are no longer using gh project board for sprint planning, so I removed the gh workflow which automatically adds the issues to the project board

### CODE REVIEW

**Comment by sutaakar** [comment]
@KPostOffice Can you please adjust the PR description to be more descriptive?

**Comment by VanillaSpoon** [comment]
Hey @KPostOffice :)
This makes sense to remove, however, maybe updating the [codeflare docs here](https://github.com/project-codeflare/.github/blob/main/profile/README.md?plain=1#L38) could also go alongside this issue.

**Comment by KPostOffice** [comment]
> Hey @KPostOffice :) This makes sense to remove, however, maybe updating the [codeflare docs here](https://github.com/project-codeflare/.github/blob/main/profile/README.md?plain=1#L38) could also go alongside this issue.

@VanillaSpoon https://github.com/project-codeflare/.github/pull/17

**Review by Bobbins228 — COMMENTED** [review]
/lgtm

**Review by VanillaSpoon — APPROVED** [review]
/approve

**Pull request merged**
