### PR TITLE
Upgrade to MCAD v1.33.0

### LINKED ISSUE #118: Build breaks with latest MCAD
The latest release of the MCAD package has incompatible (breaking) changes.

### PR DESCRIPTION
**Pull request by z103cb**
# Issue link
Closes and fixes #118 

# What changes have been made
* Updated `go.mod` + `go.sum`
* Fixed compilation issues due to new package structure
# Verification steps
Ran unit tests
## Checks
- [ ] I've made sure the tests are passing. 
- Testing Strategy
   - [X] Unit tests
   - [ ] Manual tests
   - [ ] Testing is not required for this change

### CODE REVIEW

**Review by astefanutti — CHANGES_REQUESTED** [review]
Could you please reword the commit to be more meaningful, e.g., "Upgrade MCAD to version 1.33.0".

**Comment by z103cb** [comment]
> Could you please reword the commit to be more meaningful, e.g., "Upgrade MCAD to version 1.33.0".

Done!

**Pull request merged**
