### PR TITLE
Move AppWrapper API to workload.codeflare.dev group

### LINKED ISSUE #126: Instascale - Move APIs to codeflare.dev groups
### Describe the Bug
@astefanutti MCAD [PR 591](https://github.com/project-codeflare/multi-cluster-app-dispatcher/pull/591) adjusts the CRDS from ibm.com, but while testing, it looks like InstaScale is going to need a similar migration as it's not able to find mcad.ibm.com anymore.

```
ERROR	controller-runtime.source	if kind is a CRD, it should be installed before calling Start	{"kind": "AppWrapper.mcad.ibm.com", "error": "no matches for kind \"AppWrapper\" in version \"mcad.ibm.com/v1beta1\""}
```

### Codeflare Stack Component Versions
Please specify the component versions in which you have encountered this bug.

Codeflare SDK: n/a
MCAD: Hand built and installed version of MCAD PR 591 mentioned above
Instascale: v0.0.6
Codeflare Operator: n/a
Other: 

### Steps to Reproduce the Bug

1.  Deploy MCAD with PR 591 changes:
```
git clone https://github.com/astefanutti/multi-cluster-app-dispatcher.git
cd multi-cluster-app-dispatcher
git checkout pr-12
cd deployment
helm install mcad-controller --namespace kube-system --generate-name --set  image.repository=quay.io/jbusche/pr-12 --set image.tag=latest
```
2.  Deploy InstaScale as per instructions here: https://github.com/project-codeflare/instascale#deployment
3. You need to
``` 
oc edit deploy instascale
and change:
image: quay.io/project-codeflare/instascale-controller:latest
to
image: quay.io/project-codeflare/instascale-controller:stable
4.  You'll immediately start seeing the mcad.ibm.com error above.

### What Have You Already Tried to Debug the Issue?

Mentioned above

### Expected Behavior

InstaScale should have run without error

### Screenshots, Console Output, Logs, etc.

Added above

### Affected Releases

It's going to need adjustment prior to merging the MCAD PR 591

### Additional Context
n/a

### PR DESCRIPTION
**Pull request by astefanutti**
Part of project-codeflare/adr#7

Closes #126

Follows up project-codeflare/multi-cluster-app-dispatcher#591

### CODE REVIEW

**Comment by astefanutti** [comment]
/hold

To be updated once https://github.com/project-codeflare/multi-cluster-app-dispatcher/pull/591 is merged.

**Review by sutaakar — COMMENTED** [review]
/lgtm

**Pull request merged**
